package com.mygamehub.gamefinder;
import com.mygamehub.gamefinder.dto.GameFinderRecommendRequest;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
class GameFinderRecommendationServiceTest {
    @Test void excludesLikedAndShownAndAppliesHardFilters(){var repo=mock(SteamGameRepository.class);var liked=game(1,"liked",1000,"action");var pass=game(2,"pass",5000,"action");var expensive=game(3,"expensive",20000,"action");var shown=game(4,"shown",5000,"action");when(repo.findBySteamAppIdIn(List.of(1L))).thenReturn(List.of(liked));when(repo.findRecommendationCandidates()).thenReturn(List.of(liked,pass,expensive,shown));var service=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy());var result=service.recommend(new GameFinderRecommendRequest(List.of(1L),List.of(),0,10000,false,1,15,List.of(4L)));assertThat(result).extracting(r->r.steamAppId()).containsExactly(2L);}
    @Test void returnsAtMostTwenty(){var repo=mock(SteamGameRepository.class);var liked=game(1,"liked",0,"action");var candidates=new ArrayList<SteamGame>();for(int i=2;i<40;i++)candidates.add(game(i,"g"+i,0,"action"));when(repo.findBySteamAppIdIn(List.of(1L))).thenReturn(List.of(liked));when(repo.findRecommendationCandidates()).thenReturn(candidates);var result=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy()).recommend(new GameFinderRecommendRequest(List.of(1L),List.of(),0,100000,true,1,15,List.of()));assertThat(result).hasSizeLessThanOrEqualTo(20);}
    @Test void removedGamesAreExcluded(){var repo=mock(SteamGameRepository.class);var liked=game(1,"liked",0,"action");var removed=game(2,"removed",0,"action");removed.markRemoved();when(repo.findBySteamAppIdIn(List.of(1L))).thenReturn(List.of(liked));when(repo.findRecommendationCandidates()).thenReturn(List.of(removed));var result=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy()).recommend(new GameFinderRecommendRequest(List.of(1L),List.of(),0,100000,true,1,15,List.of()));assertThat(result).isEmpty();}
    @Test void recommendationPagesAreClientSizedAndDoNotOverlap(){var repo=mock(SteamGameRepository.class);var liked=game(1,"liked",0,"action");var candidates=new ArrayList<SteamGame>();for(int i=2;i<32;i++)candidates.add(game(i,"g"+i,0,"action"));when(repo.findBySteamAppIdIn(List.of(1L))).thenReturn(List.of(liked));when(repo.findRecommendationCandidates()).thenReturn(candidates);var service=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy());var request=new GameFinderRecommendRequest(List.of(1L),List.of(),0,100000,true,1,15,List.of());var first=service.recommendPage(request,0,5);var second=service.recommendPage(request,1,5);assertThat(first.items()).hasSize(5);assertThat(first.hasNext()).isTrue();assertThat(second.items()).hasSize(5);assertThat(first.items()).extracting(r->r.steamAppId()).doesNotContainAnyElementsOf(second.items().stream().map(r->r.steamAppId()).toList());}
    @Test void tagsOnlyRanksMatchesAheadWithoutHardFilteringOthers(){var repo=mock(SteamGameRepository.class);var rpg=game(1,"rpg",0,"rpg");var action=game(2,"action",0,"action");when(repo.findBySteamAppIdIn(List.of())).thenReturn(List.of());when(repo.findRecommendationCandidates()).thenReturn(List.of(action,rpg));var service=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy());var result=service.recommend(new GameFinderRecommendRequest(List.of(),List.of("RPG"),0,100000,false,1,15,List.of()));assertThat(result).extracting(r->r.steamAppId()).containsExactly(1L,2L);}
    @Test void seedAndTagCombinationBoostsThePreferredCandidate(){var repo=mock(SteamGameRepository.class);var liked=game(1,"liked",0,"action");var plain=game(2,"plain",0,"action");var coop=game(3,"coop",0,"action","coop");when(repo.findBySteamAppIdIn(List.of(1L))).thenReturn(List.of(liked));when(repo.findRecommendationCandidates()).thenReturn(List.of(plain,coop));var service=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy());var result=service.recommend(new GameFinderRecommendRequest(List.of(1L),List.of("협동"),0,100000,false,1,15,List.of()));assertThat(result).extracting(r->r.steamAppId()).containsExactly(3L,2L);}
    @Test void noSeedsAndNoTagsIsRejected(){var repo=mock(SteamGameRepository.class);var service=new GameFinderRecommendationService(repo,new GameFinderHardFilter(),new GameTagTaxonomy());org.assertj.core.api.Assertions.assertThatThrownBy(()->service.recommend(new GameFinderRecommendRequest(List.of(),List.of(),0,100000,false,1,15,List.of()))).isInstanceOf(IllegalArgumentException.class);}
    private SteamGame game(long id,String name,int price,String... genres){var g=new SteamGame(id,name,1,1);g.updateStoreDetail("game",null,null,price==0,"KRW",price,price,0,0,"NON_ADULT",null,null,false,false,new LinkedHashSet<>(List.of(genres)),Set.of("singleplayer"),true,false,false,false);return g;}
}
